version: '3.2'
services:
  database:
    build: ./database
    volumes:
      - ./database/pgdata:/pgdata
    container_name: efeed_database_c
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=efeed
      - POSTGRES_PASSWORD=efeed
      - PGDATA=/pgdata

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/go/src/efeed_web/backend
    container_name: efeed_backend_c
    ports:
      - "8080:8080"
    links:
      - database

  # frontend:
  #   build:
  #     context: ./frontend
  #   volumes:
  #     - ./frontend:/usr/src/app
  #   container_name: sbms_frontend_c
  #   ports:
  #     - "2018:3000"
  #   links:
  #     - backend
