# build stage
FROM golang:1.11 as builder

ENV GO111MODULE=on

COPY . /go/src/efeed/backend
WORKDIR /go/src/efeed/backend

COPY go.mod /go/src/efeed/backend
COPY go.sum /go/src/efeed/backend

RUN go mod download

COPY . /go/src/efeed/backend

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o cmd/efeedWeb/efeedWeb ./cmd/efeedWeb/


# final stage
FROM scratch
EXPOSE 8080
ENTRYPOINT ["efeed/backend/cmd/efeedWeb"]
